### PR TITLE
feat: basic scaffolding 

### PR DESCRIPTION
**Pull request by kjappelbaum**
My first go at basic scaffolding. It is more complex than what we discussed, but it might give us more flexibility regarding what we can do later. By default, we record multiple input and associated `json` output files. But we also make place for providing example implementations of parsers. 

The `input`/`output` files should allow us to do things similar to what the [Berkeley team did](https://arxiv.org/abs/2212.05238). The code examples might, obviously, help with generating code. 

File formats are described with a `meta.json` schema that is not too different from what a current MARDA working group is discussing. Parser implementations have their own `meta.json` - again aligned with the MARDA efforts. 

Validation uses `pydantic` - this allows us to use all the fanciness of `pydantic` (and to generate nice docs).

### CODE REVIEW

**Comment by kjappelbaum** [comment]
@whitead, if you agree with the basic structure, I'll go ahead and add a bunch of more examples and try to do a better job with the `README.md`

**Comment by whitead** [comment]
Looks great @kjappelbaum!

One thing we should consider very early is *how* we want to parser code to look. Like if someone submits a parser and it relies on an external library, instead of python code or regular expression, is that acceptable? Would be great to add these answers to a FAQ (or we can make contributor template)

**Comment by kjappelbaum** [comment]
>. Like if someone submits a parser and it relies on an external library, instead of python code or regular expression, is that acceptable? 

Good point! My intuitive take was that the standard library and commonly used packages (`numpy`, `pandas`) are OK. Everything that is less widely used not so much. Will try to make this a bit more concrete.

**Comment by whitead** [comment]
@kjappelbaum LGTM! I vote squash & merge for PRs, go ahead and merge when you're ready. Thanks!

**Comment by kjappelbaum** [comment]
Thanks, I'll merge and then add more examples via another PR and then we might be able to announce it

**Pull request merged**
